# docker-compose.yml - Frontend Detectar con Traefik
# Ubicación: frontend-detectar/docker-compose.yml

services:
  frontend-detectar:
    build:
      context: .
    container_name: frontend-detectar
    image: frontend-detectar:latest
    ports:
      - "${FRONTEND_DETECTAR_PORT:-3200}:80"
    restart: unless-stopped
    networks:
      - mupi
    labels:
      - traefik.enable=true
      - traefik.http.routers.detectar.rule=Host(`detectar.10-161-68-134.nip.io`) && PathPrefix(`/`)
      - traefik.http.routers.detectar.entrypoints=web
      - traefik.http.routers.detectar.priority=1
      - traefik.http.services.detectar.loadbalancer.server.port=80

networks:
  mupi:
    external: true